
SELECT TOP (50000)[TipoDocIdentCons]
      ,[IdentifConsultada]
      ,[Novedad]
      ,[IdJurisdiccion]
      ,[Jurisdiccion]
      ,[Matricula]
      ,[Chip]
      ,[CedulaCatastral]
      ,[Direccion]
      ,[ConsecConsBusqParamLogSupernot]
      ,[FechaConsBusqParamLogSupernot]
      ,[ConsecConsEstJuridicoLogSupernot]
      ,[FechaConsEstJuridicoLogSupernot]
      ,[DepartamentoPredio]
      ,[MunicipioPredio]
      ,[EstadoMatricula]
      ,[NumeroPropietarios]
      ,[PersRecibePredioCodTipoIdentificacion]
      ,[PersRecibePredioNumeroIdentificacion]
      ,[PersRecibePredioPrimerApellido]
      ,[PersRecibePredioSegundoApellido]
      ,[PersRecibePredioPrimerNombre]
      ,[PersRecibePredioSegundoNombre]
      ,[PersRecibePredioNumIdTributaria]
      ,[PersRecibePredioRazonSocial]
      ,[PersRecibePredioEsPropietario]

  FROM [dbo].[Matriculas_DatosBasicos]
  WHERE idLogConsulta ='6714'
